const recipes=[
    {
        name:'Hamburger',
        category:'basics',
        image:'img/recipes/burger.jpg',
        duration:30,
        flow:[
        ]
    },
    {
        name:'Carbonara',
        category:'italian',
        image:'img/recipes/carbonara.jpg',
        duration:60,
        flow:[
        ]
    },
    {
        name:'Quesadillas',
        category:'mexican',
        image:'img/recipes/quesadillas.jpg',
        duration:30,
        flow:[
        ]
    },
    {
        name:'Tikka Masala',
        category:'asian',
        image:'img/recipes/tikkamasala.jpg',
        duration:90,
        flow:[]
    },
    {
        name:'Cookies',
        category:'sweet',
        image:'img/recipes/cookies.jpg',
        duration:120,
        flow:[]
    }
]

const categories=[
    {
        name:'basics',
        display:'Basics'
    },
    {
        name:'italian',
        display:'Italian'
    },
    {
        name:'mexican',
        display:'Mexican'
    },
    {
        name:'asian',
        display:'Asian'
    },
    {
        name:'sweet',
        display:'Sweet'
    }
]